### PR TITLE
feat: add user authentication

### PR DESCRIPTION
**Pull request by rahulbakshi4**
Pages Added : 
  - Login Page
  - Signup Page  

Functionalities Added :
  - User Authentication 
      - User can login
      - User can signup
      - user can logout

### CODE REVIEW

**Review by shilpe26 — APPROVED** [review]
Code is easy to read
The file structure is understandable
Good to merge

**Comment by scjuly19** [comment]
I am not able to signup, Can you please check once, I see a 500 error on the console.

**Comment by rahulbakshi4** [comment]
> I am not able to signup, Can you please check once, I see a 500 error on the console.

Hey, can you please check again, its working now just updated my environment variables on deployment.

**Comment by scjuly19** [comment]
> 

Yeah working fine now. Its good to merge.

**Pull request merged**
